CREATE DATABASE IF NOT EXISTS Lura;
USE Lura;

CREATE TABLE IF NOT EXISTS T_STUDENT
(
ID INT(10) PRIMARY KEY NOT NULL AUTO_INCREMENT,
NUM_MATRICULATION VARCHAR(15) NOT NULL,
NUM_CARD VARCHAR(15),
TXT_NAME VARCHAR(100) NOT NULL,
DAT_REMOVED DATETIME
);

CREATE TABLE IF NOT EXISTS T_TEACHER
(
ID INT(10) PRIMARY KEY NOT NULL AUTO_INCREMENT,
NUM_MATRICULATION VARCHAR(15) NOT NULL,
NUM_CARD VARCHAR(15),
TXT_NAME VARCHAR(100) NOT NULL,
DAT_REMOVED DATETIME
);

CREATE TABLE IF NOT EXISTS T_SUBJECT
(
ID INT(10) PRIMARY KEY NOT NULL AUTO_INCREMENT,
NUM_CODE VARCHAR(15) NOT NULL,
NUM_CREDITS INT(5) NOT NULL,
TXT_NAME VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS T_CLASSROOM
(
ID INT(10) PRIMARY KEY NOT NULL AUTO_INCREMENT,
TXT_ROOM VARCHAR(20) NOT NULL,
FL_RESTRICT TINYINT(1) DEFAULT '0' NOT NULL
);

CREATE TABLE IF NOT EXISTS T_SCHEDULE
(
ID INT(10) PRIMARY KEY NOT NULL AUTO_INCREMENT,
DAT_BEGINNING TIME NOT NULL,
DAT_END TIME NOT NULL,
TXT_DAY VARCHAR(20) NOT NULL,
TXT_DESCRIPTION VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS T_CLASS
(
ID INT(10) PRIMARY KEY NOT NULL AUTO_INCREMENT,
ID_SUBJECT INT(10) NOT NULL,
NUM_CLASS INT(10),
DAT_CREATION DATETIME,
TXT_SEMESTER VARCHAR(20),
FOREIGN KEY (ID_SUBJECT) REFERENCES T_SUBJECT(ID)
);

CREATE TABLE IF NOT EXISTS T_STUDENT_CLASS
(
ID INT(10) PRIMARY KEY NOT NULL AUTO_INCREMENT,
ID_STUDENT INT(10) NOT NULL,
ID_CLASS INT(10) NOT NULL,
DAT_ENROLLMENT DATETIME NOT NULL,
FOREIGN KEY (ID_STUDENT) REFERENCES T_STUDENT(ID),
FOREIGN KEY (ID_CLASS) REFERENCES T_CLASS(ID)
);

CREATE TABLE IF NOT EXISTS T_TEACHER_CLASS
(
ID INT(10) PRIMARY KEY NOT NULL AUTO_INCREMENT,
ID_TEACHER INT(10) NOT NULL,
ID_CLASS INT(10) NOT NULL,
DAT_ENROLLMENT DATETIME NOT NULL,
FOREIGN KEY (ID_TEACHER) REFERENCES T_TEACHER(ID),
FOREIGN KEY (ID_CLASS) REFERENCES T_CLASS(ID)
);

CREATE TABLE IF NOT EXISTS T_CLASSROOM_CLASS
(
ID INT(10) PRIMARY KEY NOT NULL AUTO_INCREMENT,
ID_CLASSROOM INT(10) NOT NULL,
ID_CLASS INT(10) NOT NULL,
FOREIGN KEY (ID_CLASSROOM) REFERENCES T_CLASSROOM(ID),
FOREIGN KEY (ID_CLASS) REFERENCES T_CLASS(ID)
);

CREATE TABLE IF NOT EXISTS T_SCHEDULE_CLASS
(
ID INT(10) PRIMARY KEY NOT NULL AUTO_INCREMENT,
ID_SCHEDULE INT(10) NOT NULL,
ID_CLASS INT(10) NOT NULL,
FOREIGN KEY (ID_SCHEDULE) REFERENCES T_SCHEDULE(ID),
FOREIGN KEY (ID_CLASS) REFERENCES T_CLASS(ID)
);

CREATE TABLE IF NOT EXISTS T_LECTURE
(
ID INT(10) PRIMARY KEY NOT NULL AUTO_INCREMENT,
ID_SCHEDULE_CLASS INT(10) NOT NULL,
DAT_DAY_OF_LECTURE DATETIME NOT NULL,
FOREIGN KEY (ID_SCHEDULE_CLASS) REFERENCES T_SCHEDULE_CLASS(ID)
);

CREATE TABLE IF NOT EXISTS T_ATTENDANCE
(
ID INT(10) PRIMARY KEY NOT NULL AUTO_INCREMENT,
ID_LECTURE INT(10) NOT NULL,
ID_STUDENT INT(10) NOT NULL,
DAT_OCCURRENCE DATETIME NOT NULL,
FOREIGN KEY (ID_LECTURE) REFERENCES T_LECTURE(ID),
FOREIGN KEY (ID_STUDENT) REFERENCES T_STUDENT(ID)
);
